name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    name: Coverage gate (${{ matrix.os }} | Py ${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install system packages (locales + tzdata)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y locales tzdata
          sudo locale-gen en_US.UTF-8 de_DE.UTF-8 fr_FR.UTF-8 ja_JP.UTF-8
          sudo dpkg-reconfigure -f noninteractive locales

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]   # pytest-cov should live in your `dev` extras

      - name: Run pytest
        run: |
          pytest --cov=pytest_tzshift --cov-report=term --cov-fail-under=95

  build-and-publish:
    name: Build & publish to PyPI
    needs: tests
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/pytest-tzshift/

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist --wheel --outdir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print_hash: true
