name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build & publish to PyPI
    needs: tests
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/pytest-tzshift/

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist --wheel --outdir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print_hash: true
